### ISSUE TITLE
`launchctl kickstart` fails in macOS 14.4

### ISSUE THREAD

**Issue by gchilds** [gavv/libASPL#8]
with `operation not permitted`

https://github.com/gavv/libASPL/blob/56775ae880568c8adf51a0d6122561e359ee377e/examples/install.sh#L47

`killall -9 coreaudiod` does work however

**Comment by gavv** [comment]
Thanks,

I can't reproduce it, but I think this should fix it: 24245bddc6104385c93ff31f3df732e913206a9f

Feel free to reopen if issue persists.
