### ISSUE TITLE
Cannot fetch properties `kAudioObjectPropertyFirmwareVersion` and `kAudioObjectPropertySerialNumber`

### ISSUE THREAD

**Issue by gchilds** [gavv/libASPL#9]
Other properties from the same set, like `kAudioObjectPropertyManufacturer`, do work. 

Calls to `AudioObjectHasProperty()` and `AudioObjectGetPropertyData()`  don't seem to even reach the `Bridge`, so the issue might lie outside libASPL.

`AudioObjectGetPropertyData()` returns `kAudioHardwareUnknownPropertyError` = `who?`.

**Comment by gavv** [comment]
TBH I don't have any idea about this property, have never used it.

I checked apple examples ([1](https://developer.apple.com/documentation/coreaudio/building_an_audio_server_plug-in_and_driver_extension?language=objc), [2](https://github.com/HelmutJ/CocoaSampleCode/tree/6564d3c02cff3daf021c59a5d08f23eca12df232/UserLandDriverReference)), they don't have kAudioObjectPropertyFirmwareVersion in source code.

**Comment by gchilds** [comment]
Yeah, no problem. I did it another way. I'll close.
